name: test01

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
      
    - name: qmake
      shell: cmd
      run: |
           cd abcd
           call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
           c:\Qt\6.5.3\msvc2019_64\bin\qmake.exe

    - name: nmake
      shell: cmd
      run: |
           cd abcd
           call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
           nmake release


    - name: Run exe (OK step)
      run: ./maintest03_OK.exe     
      continue-on-error: true

    - name: Run exe (NG step)
      run: ./maintest03_NG.exe     
      continue-on-error: true

      
    - name: Display Hello world
      run: echo "Hello world"
