name: test01

on: [push]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[compiler]') # 只有當 commit message 包含 [compiler] 字串時才執行
    runs-on: self-hosted
    
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2
     
      
    - name: qmake
      shell: cmd
      run: |
           cd abcd
           call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
           c:\Qt\6.5.3\msvc2019_64\bin\qmake.exe

    - name: nmake
      shell: cmd
      run: |
           cd abcd
           call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
           nmake release


    - name: Run exe 1 (OK step)
      run: ./maintest03_OK.exe     


    - name: Run exe 2 (OK step)
      run: ./maintest03_OK.exe     


    - name: Run exe 3 (OK step)
      run: ./maintest03_OK.exe     

    - name: Run exe 4 (OK step)
      shell: cmd
      run: |
           maintest03_OK.exe -o maintest03_OK.xml    
           $xmlContent = Get-Content -Path output.xml -Raw
           Write-Host "XML Content:"
           Write-Host $xmlContent
           
      
    - name: Display Hello world
      run: echo "Hello world" 

    - name: Git Cleanup
      run: git gc
