name: test01

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set PowerShell Execution Policy
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

    - name: Run echo command
      run: Write-Output "Hello world"
