name: test01

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Check commit message
      run: |
        if echo "${{ github.event.head_commit.message }}" | grep -q '\[compiler\]'; then
          echo "Commit message contains [compiler], proceeding with the job."
        else
          echo "Commit message does not contain [compiler], skipping the job."
          exit 0
        fi
   
    - name: Checkout code
      uses: actions/checkout@v2
     
      
    - name: qmake
      shell: cmd
      run: |
           cd abcd
           call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
           c:\Qt\6.5.3\msvc2019_64\bin\qmake.exe

    - name: nmake
      shell: cmd
      run: |
           cd abcd
           call "c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
           nmake release


    - name: Run exe 1 (OK step)
      run: ./maintest03_OK.exe     


    - name: Run exe 2 (OK step)
      run: ./maintest03_OK.exe     


    - name: Run exe 3 (OK step)
      run: ./maintest03_OK.exe     
      
    - name: Display Hello world
      run: echo "Hello world" 
